version: "3.8"

services:
  postgres:
    container_name: postgresdemo
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redisdemo
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    restart: unless-stopped

#    psql -U postgres
#    CREATE DATABASE cachedemo;

volumes:
  postgres: